function humanRobotMarkup(item, nextItem) {
  const root = 'assets/projects/human-robot/';
  const figure = (name, caption, cls = '') => `<figure class="hr-figure ${cls}"><a href="${root}${name}.jpg" target="_blank" rel="noreferrer" aria-label="Enlarge: ${caption}"><img src="${root}${name}.jpg" alt="${caption}" loading="lazy"></a><figcaption>${caption}</figcaption></figure>`;
  const gallery = (items, cls = '') => `<div class="hr-gallery ${cls}">${items.map(([name,caption]) => figure(name,caption)).join('')}</div>`;
  const heading = (id, number, title, copy) => `<header class="hr-heading" id="${id}"><span>${number}</span><div><h3>${title}</h3><p>${copy}</p></div></header>`;
  const comparisons = [
    ['reference-lua','Lua flowerpot','Turns plant conditions into expressions that prompt care.'],
    ['reference-cradle','Robotic cradle','Responds to crying with soothing sound and movement.'],
    ['reference-chair','Massage chair','Translates user settings into movement and bodily contact.'],
    ['reference-bin','Garbage bin','Opens through a gesture—the starting point for my design.'],
    ['reference-thermomix','Thermomix TM5','Guides cooking through coordinated prompts and actions.']
  ];
  const autonomy = [
    ['Reactive','evolution-02-0','A wave or tap opens the bin, reducing the need to touch the lid.'],
    ['Interactive','evolution-03-1','The bin is imagined recognizing waste and reminding people to sort or dispose of it.'],
    ['Adaptive','evolution-04-0','A mobile assistant is proposed to collect food waste, process it and feed plants.'],
    ['Innovative','evolution-05-2','A speculative network connects the bin to other robots through signals, material exchange and charging.']
  ];
  return `<article class="hr-case">
  <section class="hr-hero"><div><p class="hr-label">Human–robot interaction · Industrial design · ${item.year}</p><h1>Human<br><span>& Robot</span></h1><p class="hr-subtitle">G2 / A kitchen robot in a domestic ecology.</p><p class="hr-intro">From an everyday garbage bin to a mobile kitchen companion: a design inquiry into collecting food waste, transforming it, and exchanging resources with other household robots.</p></div><figure><img src="${root}hero.jpg" alt="G2 kitchen robot digital rendering with wheeled base and flexible collection arm"><figcaption>G2 · Digital concept rendering</figcaption></figure></section>
  <section class="hr-facts" aria-label="Project facts"><div><span>My role</span><p>Research, interaction scenarios, sketching, cardboard prototyping and digital modeling.</p></div><div><span>Design question</span><p>How can a robot participate in household material cycles, rather than perform one isolated task?</p></div><div><span>Project scope</span><p>Academic design proposal, with a physical form-and-mechanism mock-up and digital renders.</p></div></section>
  <nav class="hr-nav" aria-label="Project sections"><a href="#hr-identify">01 / Identify</a><a href="#hr-explore">02 / Explore</a></nav>
  <section class="hr-part" id="hr-identify"><div class="hr-research-opening"><header><p class="hr-label">Part 01 / Identify Robot</p><h2>What makes<br> an object a robot?</h2><p>I surveyed 30 everyday examples and compared five through sensing, action and human interaction, choosing the garbage bin for further exploration.</p></header><figure class="hr-figure"><a href="${root}robot-survey.jpg" target="_blank" rel="noreferrer" aria-label="Enlarge the original 30-example robot survey"><img src="${root}robot-survey.jpg" alt="Original visual survey of 30 everyday objects and machines" loading="lazy"></a></figure></div>
  ${heading('hr-five','01.1','Finding of the five robots','Five reference products, compared through how they respond to people.')}
  <div class="hr-comparisons">${comparisons.map(([img,name,copy])=>`<article><a class="hr-reference-image" href="${root}${img}.jpg" target="_blank" rel="noreferrer" aria-label="Enlarge ${name} research reference"><img src="${root}${img}.jpg" alt="${name} · Reference product" loading="lazy"></a><h4>${name}</h4><p>${copy}</p></article>`).join('')}</div>
  ${heading('hr-evolution','01.2','Extend / four levels of autonomy','Four speculative design scenarios—not a technical rating—trace the bin’s shift from a responsive object to a connected household partner.')}
  <div class="hr-autonomy">${autonomy.map(([title,img,copy])=>`<article><a class="hr-reference-image" href="${root}${img}.jpg" target="_blank" rel="noreferrer" aria-label="Enlarge ${title} scenario sketch"><img src="${root}${img}.jpg" alt="${title}: original garbage-bin scenario sketch" loading="lazy"></a><h4>${title}</h4><p>${copy}</p></article>`).join('')}</div>
  ${heading('hr-alternatives','01.3','Expand / a robot needs more than a body','Alternative mechanisms, propulsion, sensing and communication were explored together. The first orange concept links movement, collection, processing and exchange before the later G2 form is developed.')}
  <div class="hr-technical">${figure('evolution-08-2','Early mobile waste-collection concept.')} ${figure('evolution-09-1','Early sectional sketch: collection, mixing, heating and filtration.')}<dl><div><dt>Move & navigate</dt><dd>Hub motors and multidirectional wheels; ultrasonic sensing proposed for obstacle awareness.</dd></div><div><dt>Locate & collect</dt><dd>Odor and sound sensing explored as alternatives to exclusively visual interaction.</dd></div><div><dt>Process & contain</dt><dd>Mixing blades, heating, drying and carbon filtration investigated as possible components. UV treatment appears as an early research option.</dd></div><div><dt>Communicate & exchange</dt><dd>Phone signals, scheduled instructions and robot-to-robot exchanges extend the interaction beyond disposal.</dd></div></dl></div>
  ${gallery([['evolution-10-6','Propulsion reference: hub motor.'],['evolution-10-5','Mobility reference: Mecanum wheel.'],['evolution-10-2','Sensing reference: ultrasonic sensor.'],['evolution-10-3','Processing reference: mixing blade.']], 'hr-small-grid')}
  ${heading('hr-ecosystem','01.4','Ecosystem with other robots','The waste robot is imagined as one participant in a shared domestic system. Resource and service exchanges give purpose to its mobility and processing functions.')}
  <div class="hr-pair">${figure('evolution-12-0','Original ecosystem map connecting the proposed household robots.')}<div class="hr-exchanges"><article><span>Schedule</span><h4>Alarm-clock robot</h4><p>Receive timed instructions and travel to a designated collection point. Collaborator: Shub.</p></article><article><span>Organic material</span><h4>Farming robot</h4><p>Collect vegetable roots and return proposed liquid nutrients. Collaborator: Zeo.</p></article><article><span>Distribution</span><h4>Transport robot</h4><p>Pass on the proposed dried output for transport. Collaborator: Zitong.</p></article><article><span>Energy</span><h4>Ceiling robot</h4><p>Receive charging support within the shared system. Collaborator: Hank.</p></article></div></div>
  ${gallery([['evolution-13-1','Interaction sketches: scheduling, collection, exchange and charging.'],['evolution-11-4','The proposed material exchange with the farming system.']], 'hr-two')}
  <p class="hr-transition">The system proposal sets the next design problem: how could this robot actually fit into a kitchen and reach the places where food waste appears?</p>
  </section>
  <section class="hr-part" id="hr-explore"><header class="hr-part-title"><p>Part 02 / Explore</p><h2>Making G2 tangible.</h2><p>Domestic observation, technical references and quick prototypes translate the broad ecosystem into a product-scale proposal. The sequence follows Notion: exploration, technology, storyboard, scene and prototype, then rendering.</p></header>
  ${heading('hr-context','02.1','Where does food become waste?','The journey study identifies food preparation and the end of a meal as two key moments. Kitchen and dining observations then turn that insight into questions of reach, height and hands-free collection.')}
  <ol class="hr-journey"><li><span>01</span>Buy food</li><li><span>02</span>Store</li><li class="is-focus"><span>03 / Collection opportunity</span>Prepare food</li><li><span>04</span>Eat</li><li class="is-focus"><span>05 / Collection opportunity</span>Clear the table</li></ol>
  ${gallery([['development-04-0','Kitchen field study: worktop, circulation and preparation area.'],['development-05-1','Disposal after eating: transferring scraps from a plate.'],['development-05-2','Wiping the tabletop introduces a second collection action.']], 'hr-three')}
  <details class="hr-details"><summary>Research context / original journey and waste studies</summary>${gallery([['development-03-0','Original household food journey.'],['development-02-0','Food-waste composition chart collected during the project.'],['development-02-1','Per-capita waste chart collected during the project.'],['development-02-2','Compaction and waste-flow reference.']], 'hr-two')}<p>These charts are retained as historical research material. Their dates and source context are not fully recoverable here, so no numerical claims are carried into the project’s conclusions.</p></details>
  ${heading('hr-sketches','02.2','A body that can reach the worktop','Early sketches compare elevated bins, extending collectors, movable bodies and different ways of approaching a table. The emerging direction combines a low mobile base, a lifting platform and a flexible collecting arm.')}
  ${gallery([['development-06-0','Elevating the container to the working surface.'],['development-06-3','Exploring movable container architectures.'],['development-06-4','Approaching a table edge.'],['development-06-6','Comparing reach and collection configurations.']], 'hr-sketches')}
  ${heading('hr-technology','02.3','Technology detail / translating the requirements','Biomimetic smell research, flexible-arm references, wheel assemblies and lift mechanisms informed the proposal. These references guide a design direction; they do not establish a completed sensing or control system.')}
  <div class="hr-tech-grid"><article>${figure('development-07-0','Flexible-arm research reference.')}<h4>Reach</h4><p>A flexible intake is proposed to extend the collection point beyond the rigid container.</p></article><article>${figure('development-11-1','Lift and base development sketches.')}<h4>Lift</h4><p>A scissor mechanism bridges the low traveling position and the kitchen worktop.</p></article><article>${figure('development-07-3','Wheel and drive assembly research reference.')}<h4>Move</h4><p>A compact wheeled base supports movement around furniture and working areas.</p></article></div>
  <div class="hr-design-note"><h4>Processing is a design intention</h4><p>G2 is conceived to collect food waste and use heating and drying toward a fertilizer-related output, as described in Notion. The archive does not establish nutrient quality, compost maturity, energy use or sanitation performance; those remain engineering and testing questions.</p></div>
  ${heading('hr-storyboard','02.4','Storyboard / from a meal to a clean surface','The original ten-frame sequence links eating, clearing, spills and cleaning to an imagined robot response. Keeping the sequence together shows how the proposal grows out of a domestic situation.')}
  ${figure('development-09-0','Original ten-frame storyboard: meal, cleanup, waste contact and the imagined collection behavior.', 'hr-storyboard')}
  ${heading('hr-prototype','02.5','Scene & prototype / learning at physical scale','A cardboard model explores the mobile base and scissor-lift motion. This is a form-and-mechanism mock-up, not an autonomous working robot. Its role is to make proportion, clearance and movement available for inspection.')}
  ${gallery([['development-10-3','Lowered platform and wheeled base.'],['development-10-2','Intermediate lift position.'],['development-10-4','Extended scissor structure.'],['development-10-0','Detail of the scissor joint.']], 'hr-four')}
  ${gallery([['development-11-0','Body and base proportions refined through drawing.'],['development-11-2','Collector, enclosure and mechanism refined together.']], 'hr-two')}
  <div class="hr-specs"><div><strong>400 × 400 mm</strong><span>Proposed plan footprint</span></div><div><strong>400 mm</strong><span>Proposed lowered height</span></div><div><strong>750 mm</strong><span>Proposed raised height</span></div></div>
  ${heading('hr-rendering','02.6','Rendering / one robot, two working heights','The digital proposal brings the base, lifting platform, container and flexible collector together. The kitchen scenes illustrate intended use and scale, rather than a tested deployment.')}
  ${gallery([['render-low','G2 in its lowered traveling position.'],['render-raised','G2 with the scissor platform extended.']], 'hr-two hr-renders')}
  ${figure('render-kitchen','G2 positioned beside a kitchen worktop · Digital scenario.', 'hr-scene')}
  ${gallery([['render-collection','Collection at the worktop · Digital scenario.'],['development-13-1','Flexible collector detail · Digital model.']], 'hr-two')}
  <details class="hr-details"><summary>Form & material reference board</summary>${gallery([['development-08-1','Rounded product surface and accent reference.'],['development-08-4','Wheel-to-body integration reference.'],['development-08-5','Tactile control-detail reference.'],['development-08-6','Domestic material and color context.']], 'hr-four')}<p>Reference imagery from the original mood board; not G2 design outputs.</p></details>
  <div class="hr-conclusion"><h3>Designing the relationship,<br>not only the robot.</h3><p>The project develops a line from responsive object to mobile assistant to interconnected system. Its tangible contribution is the interaction proposal, original sketches, cardboard mechanism study and digital G2 design. The next step would be testing collection, obstacle handling, safe lifting and the actual treatment of food waste.</p></div>
  </section>
  <section class="hr-sources"><p class="hr-label">Original project & further context</p><h2>Keep the process accessible.</h2><div><a href="${item.source}" target="_blank" rel="noreferrer">Notion / full narrative ↗</a><a href="${root}evolution-process.pdf" target="_blank" rel="noreferrer">Part 01 / evolution & ecosystem PDF ↗</a><a href="${root}g2-development.pdf" target="_blank" rel="noreferrer">Part 02 / G2 development PDF ↗</a></div><p>Sequence and project evidence: Chang Su’s Human & Robot archive, CCA, 2020. Ecosystem collaborators are credited beside their robot concepts. The original Notion references include Hugh Durrant-Whyte’s “What is a robot?” and discussions of robotics, AI and autonomy.</p></section>
  <a class="next-project" href="project.html?project=${nextItem.slug}"><span>Next project</span><strong>${nextItem.title}</strong><i>→</i></a></article>`;
}
