// Sequence follows the Notion archive; image IDs identify source part/page/image.
function wildHybridMarkup(item, nextItem) {
  const root = 'assets/projects/wild-hybrid/';
  const group = (title, copy, images, style = '') => `<section class="wild-study ${style}"><div class="wild-study-heading"><h3>${title}</h3><p>${copy}</p></div><div class="wild-images" style="--count:${Math.min(images.length, 4)}">${images.map(([file, caption]) => `<figure><a href="${root}${file}.jpg" target="_blank" rel="noreferrer" aria-label="Enlarge: ${caption}"><img src="${root}${file}.jpg" alt="${caption}" loading="lazy"></a><figcaption>${caption}</figcaption></figure>`).join('')}</div></section>`;
  const chapter = (number, title, intro, content, transition) => `<section class="wild-chapter" id="wild-part-${number}"><header class="wild-chapter-heading"><p>Part 0${number}</p><div><h2>${title}</h2><p>${intro}</p></div></header>${content}<p class="wild-transition"><span>What carries forward ↗</span>${transition}</p></section>`;
  return `<article class="wild-case">
    <section class="wild-hero"><div><p class="eyebrow">Research through Design · 2021</p><h1>Wild<br>Hybrid</h1><p class="wild-deck">Plant-like human life extension.</p><p>A thinking-through-making inquiry into bodies, plants, and artificial objects. Could growth and attachment suggest a different way of moving through the world?</p><div class="wild-tags">Body experiments / Multispecies inquiry / Digital fabrication</div></div><figure><img src="${root}4-13-0.jpg" alt="Digital render of a thorned foot extension with an arching strap"><figcaption>Climbing imagined through a plant-like body extension · Digital concept</figcaption></figure></section>
    <div class="wild-context"><p><span>My role</span>Research, observation, sketches, physical prototyping and digital modeling.</p><p><span>Method</span>Research through Design and art intervention: observe, make, wear, and reflect.</p><p><span>Proposition</span>From borrowing the appearance of plants to exploring their growth, contact and attachment.</p></div>
    <nav class="wild-nav" aria-label="Wild Hybrid chapters"><a href="#wild-part-1">01 / Drawing with body</a><a href="#wild-part-2">02 / Body to plant</a><a href="#wild-part-3">03 / Growing & climbing</a><a href="#wild-part-4">04 / Wearing</a></nav>
    ${chapter(1, 'Drawing with body', 'An ordinary walk to my cousin’s home became a record of small bodily rituals. Moving the point of attention from the eyes to the knees and feet turned familiar actions into drawing tools.',
      group('An everyday route, observed differently', 'Putting on shoes, opening doors, finding the way, looking for a cat and triggering a light: movement responds to habits, surroundings and curiosity.', [['1-02-2','Slip-on shoes: the foot negotiates the opening.'],['1-03-2','Opening the door: a familiar bodily routine.'],['1-05-3','Bending down to search for a cat.'],['1-06-1','A stamp of the foot activates the light.']], 'compact') +
      group('What if the knees could see?', 'A displaced viewpoint and a leg’s shadow make an overlooked part of the body the subject of attention. Reading and walking become unfamiliar again.', [['1-08-0','The leg as an independent observer.'],['1-09-0','Shadow study: movement becomes a silhouette.'],['1-10-2','Reading from the knee’s viewpoint.']], 'compact') +
      group('Body → tool → trace', 'Brushes attached near the knee record joint movement; textured material at the foot translates pressure into stamps. The resulting marks connect an action to its material evidence.', [['1-12-2','Knee-mounted brush.'],['1-12-0','Brush traces from leg movement.'],['1-13-3','Textured stamping material.'],['1-13-2','Foot-pressure marks.']]),
      'The body is not only a user of tools. Its joints, rhythms and contact points can generate the design inquiry itself.')}
    ${chapter(2, 'From body to plant', 'Multispecies ethnography began with everyday plant encounters. A Chinese prickly ash (Zanthoxylum bungeanum) on the walking route became the central actor: familiar as food, but physically insistent when its thorns caught clothing.',
      group('Choosing a wild actor', 'Mint, winter jasmine, a money tree, a succulent and prickly ash offered different relations to daily life. The prickly ash connected taste, touch and movement in the same encounter.', [['2-02-0','Mint'],['2-02-1','Winter jasmine'],['2-02-2','Money tree'],['2-02-4','Succulent']], 'compact') +
      group('A tree is also a situation', 'Fieldwork followed the narrow path, neighboring buildings, groundcover and watering arrangements, then moved closer to bark, thorn bases and new buds.', [['2-06-1','The narrow planting strip beside the buildings.'],['2-06-3','Branches, walls and a watering hose.'],['2-07-2','Thorn structure and its broad attachment.'],['2-10-0','New buds and paired thorns.']]) +
      group('Recording contact', 'Foil impressions preserve surface relief. Scratching fruit makes the thorn’s contact visible without using human skin; the record is an exploratory material comparison, not a measured biological test.', [['2-08-1','Foil impression of bark and thorn relief.'],['2-08-3','A second surface impression.'],['2-09-1','Scratching an apple skin.'],['5-02-0','Testing contact against a tomato.']]) +
      group('Material experiments: puncture, hook, resist', 'Fruit, foam, balloons and clay translate the same thorn into different tactile and acoustic events. These trials investigate how a small structure can change the behavior of another material. <a class="wild-source" href="assets/projects/wild-hybrid/material-experiments.pdf" target="_blank" rel="noreferrer">Full material-experiment record ↗</a>', [['5-02-3','Blueberry: puncture marks.'],['5-03-0','Foam: catching and surface damage.'],['5-04-1','Balloon: hooking and tension.'],['5-05-1','Water balloon: contact before rupture.'],['5-06-0','Clay attached to different thorns.'],['5-06-1','Clay impressions compared.'],['5-07-0','Sketching the thorn’s base and tip.'],['5-09-0','A small branch structure assembled in foam.']], 'compact'),
      'A thorn is more than a sharp outline: its base, curvature and contact with other materials suggest attachment as a design operation.')}
    ${chapter(3, 'Growing and climbing', 'The inquiry shifts from isolated thorns to growth over time. Branching, bending and entanglement become speculative rules for making, rather than patterns to copy onto a product.',
      group('Reading growth through constraints', 'Buds and thorns suggest a comparison with bodily joints. Ties, nearby surfaces, water and temperature frame the study of direction; the body–plant comparison is a design interpretation.', [['3-04-0','Branches constrained by the built environment.'],['3-04-2','Tied branches and emerging leaves.'],['3-04-3','A growing node between thorns.']], 'compact') +
      group('A grammar of changing direction', 'What happens if a branch is released, keeps extending, or turns back on itself? Sketches and collages imagine recoil, repeated branching and spiraling growth.', [['3-05-1','Directional branching study.'],['3-07-1','Linear, alternating and spiral paths.'],['3-06-0','Speculative extended-growth collage.'],['3-07-0','Speculative spiral-growth collage.']]) +
      group('Not a solitary organism', 'Aphids, spiders and caterpillars entered the visual research as possible participants in a branch’s changing environment. These speculative scenarios ask who else might inhabit or redirect a growing structure.', [['3-08-1','Aphid reference from the research archive.'],['3-10-0','Spider reference from the research archive.'],['3-11-0','Caterpillar reference from the research archive.']], 'compact'),
      'The next step is to wear the translation: use growth and attachment to imagine climbing as an alternative to ordinary walking.')}
    ${chapter(4, 'Wearing', 'Inspired by Rebecca Horn’s body-extension performances, these experiments move between the knee, hand and foot. Each prototype asks where an artificial extension could attach, and how plant-like features might change bodily contact.',
      group('From observation to a wearable proposition', 'Early directions included defensive forms and tactile communication. The developed direction returned to the walking body: extending its contact points toward an imagined climbing action.', [['4-06-0','First knee and foot extension sketches.'],['4-07-0','Translating the thorn into a wearable patch.'],['4-07-1','Branch growth mapped onto a limb.']], 'compact') +
      group('Knee / a new contact surface', 'Clay patches test placement and scale. Thorn-like protrusions are then explored as a digitally modeled surface.', [['4-07-2','Clay and thorns: an initial surface model.'],['4-08-1','Placement on the lower leg.'],['4-08-2','Wearable clay patch.'],['4-08-0','Digital thorn-surface study.']]) +
      group('Hand / growing outward', 'Soft modeling studies move from additional fingers to thorn-like projections. The sketches and models explore extension, grip and the transition between hand and object.', [['4-09-1','Digital hand-growth study.'],['4-10-0','Soft material on a hand form.'],['4-10-2','Thorn-like extensions modeled on a glove.'],['4-10-4','A freestanding model of the extended hand.']]) +
      group('Hand / making a printable fragment', 'The form is refined through sketches and a dark thorned component. Only part of the larger proposal was 3D printed because of its size; handling photographs document the prototype fragment, not a complete climbing device.', [['4-11-6','Form-development sketches.'],['4-11-1','Fabricated thorned fragment.'],['4-11-2','Checking scale and contact by hand.'],['4-11-4','Holding the printed component.']]) +
      group('Foot / pressure, attachment, support', 'Heel and forefoot contact studies locate the extension on the body. Improvised straps and sketches explore how a wearable structure could be secured.', [['4-12-0','Marking heel and forefoot contact.'],['4-12-1','Testing contact while standing.'],['4-12-2','Exploring a simple strap attachment.'],['4-12-4','Developing the foot-extension structure.']], 'compact') +
      group('Plant-like body extension', 'The final digital proposal combines an arching strap, an underfoot structure and outward-facing thorn forms. These are speculative design renders, not validated climbing or safety equipment.', [['4-13-0','Underfoot geometry and attachment strap.'],['4-13-2','Thorn forms distributed along the edge.'],['4-13-1','Digital wearing study.'],['4-13-3','Rear view of the proposed extension.']], 'outcome'),
      'Making shifted the question from “What does a plant look like?” to “How might a body act differently through a plant-like extension?”')}
    <section class="wild-archive"><p class="eyebrow">Research context & original records</p><h2>Follow the inquiry in full.</h2><p>The four-part sequence follows my Notion archive. The original process books retain the detailed observations, alternative directions and reference material behind this edited visual narrative.</p><div class="wild-downloads">${['Body drawing','Wild actor','Growing & climbing','Wearing'].map((label,i)=>`<a href="${root}part-${i+1}.pdf" target="_blank" rel="noreferrer">0${i+1} / ${label} <span>PDF ↗</span></a>`).join('')}</div><p class="wild-reference">Art and method references: Rebecca Horn’s body-extension performances; Olafur Eliasson’s <em>Connecting Cross Country With a Line</em>; <em>Infinity Studies: Monotony</em>; Odom et al. (2016), <em>From Research Prototype to Research Product</em>. Reference imagery is identified in captions; experiments and design development are my own project documentation.</p><a class="wild-source" href="${item.source}" target="_blank" rel="noreferrer">Read the original Notion project ↗</a></section>
    <a class="next-project" href="project.html?project=${nextItem.slug}"><span>Next project</span><strong>${nextItem.title}</strong><i>→</i></a>
  </article>`;
}
